<form action="register" method="post">
<fieldset><legend>%("Not registered yet?");</legend>
<div class="c">
	<input type="hidden" name="do" value="register" />
	<input type="checkbox" name="agbok" />
	<a href="/terms">%("I accept the terms of usage.");</a>
	<input type="text" name="email" value="%("email address");" size="30" />
	<button type="submit">%("register");</button>
</div>
</fieldset>
</form>
