<div class="mmenu alliance">
<ul>
	<li><a href="map">Karte</a></li>
	<li><a href="player">Spieler</a></li>
	<li><a id="mactive" href="alliance">Allianz</a></li>
	<li><a href="stats">Statistiken</a></li>
	<li><a href="demo">Demo</a></li>
	<li><a href="help">Hilfe</a></li>
</ul>
</div>

<div class="smenu alliance">
<ul>
	<li class="i0"><h1>Allianz</h1>
		<a href="alliance">Mitglieder</a>
		<a href="alliance-forum">Forum</a>
		<a href="">Bewerbungen</a>
		<a href="">Transmitter</a>
	</li>
	<li class="i1"><h1>Diplomatie</h1>
		<a href="">Nachrichten</a>
		<a href="">Freunde</a>
		<a href="">Feinde</a>
		<a href="">Verträge</a>
	</li>
	<li class="i2"><h1>Administration</h1>
		<a href="">Mitglieder</a>
		<a href="">Logo</a>
	</li>
	<li class="i3"><h2>Rang: %string rank.name;</h2></li>
</ul>
</div>

%include "include/alliance-banner.inc";
