<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>DEMO Conquer-Space.net</title>
	<link rel="stylesheet" type="text/css" href="%string Session.GP.css;standard.css" />
	<link rel="stylesheet" type="text/css" href="%string Session.GP.css;cqs.css" />
	<link rel="stylesheet" type="text/css" href="%string Session.GP.demo;image-submenu.css" />
	<link rel="stylesheet" type="text/css" href="%string Session.GP.demo;image-background.css" />
	<meta name="robots" content="noindex" />
</head>
<body>

%set player Session.player;
%set alliance Session.alliance;
%set locale Session.locale;
%include "include/status-line.inc";

<div class="mmenu demo">
<ul>
	<li><a href="map">Karte</a></li>
	<li><a href="player">Spieler</a></li>
	<li><a href="alliance">Allianz</a></li>
	<li><a href="stats">Statistiken</a></li>
	<li><a id="mactive" href="demo">Demo</a></li>
	<li><a href="help">Hilfe</a></li>
</ul>
</div>

<div class="smenu demo">
<ul>
	<li class="i0"><h1>Demo</h1>
		<a href="">Irgendwas</a>
		<a href="">Nochwas</a>
		<a href="">Und mehr</a>
	</li>
	<li class="i1"><h1>Demo</h1>
		<a href="">Irgendwas</a>
		<a href="">Nochwas</a>
		<a href="">Und mehr</a>
	</li>
	<li class="i2"><h1>Demo</h1>
		<a href="">Irgendwas</a>
		<a href="">Nochwas</a>
		<a href="">Und mehr</a>
	</li>
	<li class="i3"><h1>Unglaublich</h1></li>
</ul>
</div>
