<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
%include "include/default.inc";
<head>
	<title>Conquer-Space.net</title>
	<base href="%string System.url;/DesignUlf/" />
	<link rel="stylesheet" type="text/css" href="%string Session.GP.css;standard.css" />
	<link rel="stylesheet" type="text/css" href="%string Session.GP.css;cqs.css" />
	<link rel="stylesheet" type="text/css" href="%string Session.GP.demo;morgo-example.css" />
<!--	<link rel="stylesheet" type="text/css" href="%string Session.GP.demo;debug.css" />-->
	<meta name="robots" content="noindex" />
</head>
<body>
%include "include/status-line.inc";
