%include "include/head.inc";

<div class="mmenu help">
<ul>
	<li><a href="map">Karte</a></li>
	<li><a href="player">Spieler</a></li>
	<li><a href="alliance">Allianz</a></li>
	<li><a href="stats">Statistiken</a></li>
	<li><a href="demo">Demo</a></li>
	<li><a id="mactive" href="help">Hilfe</a></li>
</ul>
</div>

<div class="smenu help">
<ul>
	<li><h1>Hilfe</h1>
		<a href="help">Allgemeines</a>
		<a href="?">Einstellungen</a>
		<a href="?">Support</a>
		<a href="?">Quota</a>
	</li>
</ul>
</div>
