%include "include/head.inc";

<div class="mmenu stats">
<ul>
	<li><a href="map">Karte</a></li>
	<li><a href="player">Spieler</a></li>
	<li><a href="alliance">Allianz</a></li>
	<li><a id="mactive" href="stats">Statistiken</a></li>
	<li><a href="demo">Demo</a></li>
	<li><a href="help">Hilfe</a></li>
</ul>
</div>

<div class="smenu stats">
<ul>
	<li><h1>Statistiken</h1>
		<a href="?">Kolonien</a>
	</li>
	<li><h1>Top</h1>
		<a href="?">Spieler</a>
		<a href="?">Allianzen</a>
	</li>
	<li><h1>Suchen</h1>
		<a href="?">Spieler</a>
		<a href="?">Allianzen</a>
	</li>
</ul>
</div>
